{% set name = "jj" %}
{% set version = "0.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/martinvonz/jj/archive/v{{ version }}.tar.gz
  sha256: c38d98d7db42f08b799f5c51f33cd8454867bc4862a15aa0897b72f2d32eea0a

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - libgit2  # [win]
    - openssl
    - zlib

test:
  commands:
    - jj --help

about:
  home: https://github.com/martinvonz/jj
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Git-compatible distributed version control system
  dev_url: https://github.com/martinvonz/jj

extra:
  recipe-maintainers:
    - danielnachun
