{% set name = "jj" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/martinvonz/jj/archive/v{{ version }}.tar.gz
  sha256: ed49b1c01ee6086bb782a465a4437e2f1b66f43bcf39c231df2b261091ab114b

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - libgit2  # [win]
    - openssl
    - zlib

test:
  commands:
    - jj --help

about:
  home: https://github.com/martinvonz/jj
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Git-compatible distributed version control system
  dev_url: https://github.com/martinvonz/jj

extra:
  recipe-maintainers:
    - danielnachun
