context:
  version: "0.39.0"

package:
  name: jj
  version: ${{ version }}

source:
  url: https://github.com/martinvonz/jj/archive/v${{ version }}.tar.gz
  sha256: 52a60f058cf66ba3dc0bf69f189e99763b33b6770b3068b2be4fe76ecd287282

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - if: win
      then: libgit2
    - openssl
    - zlib

tests:
  - script:
      - jj --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Git-compatible distributed version control system
  homepage: https://github.com/martinvonz/jj
  repository: https://github.com/martinvonz/jj

extra:
  recipe-maintainers:
    - danielnachun
