context:
  version: "0.30.0"

package:
  name: jj
  version: ${{ version }}

source:
  url: https://github.com/martinvonz/jj/archive/v${{ version }}.tar.gz
  sha256: 86f8df1e4e76c6a4bcdb728fa74876bacf931641157d16f6e93ebeb5bac0151c

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - if: win
      then: libgit2
    - openssl
    - zlib

tests:
  - script:
      - jj --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Git-compatible distributed version control system
  homepage: https://github.com/martinvonz/jj
  repository: https://github.com/martinvonz/jj

extra:
  recipe-maintainers:
    - danielnachun
