context:
  version: "0.29.0"

package:
  name: jj
  version: ${{ version }}

source:
  url: https://github.com/martinvonz/jj/archive/v${{ version }}.tar.gz
  sha256: 57df34a06b1d2125ccd6e8383ea08f24160c48e33e9daecd883a2e59567a9fd9

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - if: win
      then: libgit2
    - openssl
    - zlib

tests:
  - script:
      - jj --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Git-compatible distributed version control system
  homepage: https://github.com/martinvonz/jj
  repository: https://github.com/martinvonz/jj

extra:
  recipe-maintainers:
    - danielnachun
