context:
  version: "0.41.0"

package:
  name: jj
  version: ${{ version }}

source:
  url: https://github.com/martinvonz/jj/archive/v${{ version }}.tar.gz
  sha256: 135bf1df883a7f50c96907d87a246ec9fbe885d2d4fe4d1bf7d34d98dec910ba

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - if: win
      then: libgit2
    - openssl
    - zlib

tests:
  - script:
      - jj --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Git-compatible distributed version control system
  homepage: https://github.com/martinvonz/jj
  repository: https://github.com/martinvonz/jj

extra:
  recipe-maintainers:
    - danielnachun
