context:
  version: "0.40.0"

package:
  name: jj
  version: ${{ version }}

source:
  url: https://github.com/martinvonz/jj/archive/v${{ version }}.tar.gz
  sha256: ca45f2b866ce2fa25c7fc485e6b168cf055a39b1eab0ea170738c0b7e86d3b33

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - if: win
      then: libgit2
    - openssl
    - zlib

tests:
  - script:
      - jj --help

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Git-compatible distributed version control system
  homepage: https://github.com/martinvonz/jj
  repository: https://github.com/martinvonz/jj

extra:
  recipe-maintainers:
    - danielnachun
